# Generated by Django 5.1.1 on 2026-02-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotNo', models.IntegerField(unique=True)),
                ('isCovered', models.BooleanField(default=False)),
                ('isEVCharging', models.BooleanField(default=False)),
                ('isOccupied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['slotNo'],
            },
        ),
    ]
